databases:
  - name: ruby_chat_tw
    databaseName: ruby_chat_tw
    user: ruby
    plan: free

services:
  - type: web
    name: ruby_chat_tw
    runtime: ruby
    plan: free
    region: singapore
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby_chat_tw
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
